# This file was generated by GoReleaser. DO NOT EDIT.
cask "cipher" do
  version "0.1.0"

  on_macos do
    on_intel do
      sha256 "198574d9bec0a8181fc4f8d49d6892c5e16a90973c0a040e5878dbbbda184677"
      url "https://github.com/dcadolph/cipher/releases/download/v#{version}/cipher_#{version}_Darwin_x86_64.tar.gz"
    end
    on_arm do
      sha256 "f6836b8d8020ff42c9b953414998f6407e7ff3aec3362f321cf16b122b22bb3a"
      url "https://github.com/dcadolph/cipher/releases/download/v#{version}/cipher_#{version}_Darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "2e71ab4e6a90bdd9bb1bca539dcfa0038bcee81981a2cda817bfd0ed9d32e5eb"
      url "https://github.com/dcadolph/cipher/releases/download/v#{version}/cipher_#{version}_Linux_x86_64.tar.gz"
    end
    on_arm do
      sha256 "4fd75b5796b487f96ba5fc4b59151b86d51adbedbff9a7af9f85e20e098e7828"
      url "https://github.com/dcadolph/cipher/releases/download/v#{version}/cipher_#{version}_Linux_arm64.tar.gz"
    end
  end

  name "cipher"
  desc "Programmatic SOPS for Go. Encrypt, decrypt, rotate, walk, edit, and audit secret files."
  homepage "https://github.com/dcadolph/cipher"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "cipher"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/cipher"]
    end
  end

  # No zap stanza required

end
