# This file was generated by GoReleaser. DO NOT EDIT.
cask "kibble" do
  version "0.19.2"

  on_macos do
    on_arm do
      sha256 "f425b851423f8b40fa1bfa05d60c0c99ceebc4522165fdf9b41271fce3c4ae4f"
      url "https://github.com/dcadolph/kibble/releases/download/v#{version}/kibble_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "b2f331f2865fb7ee138d51e96cdf5f7a91b1b41e7d8d5596bc8c469bcb565fe4"
      url "https://github.com/dcadolph/kibble/releases/download/v#{version}/kibble_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "4ca0217b01877fd6319114238aec2bc183572b2d9e6e9aa63094757265da7161"
      url "https://github.com/dcadolph/kibble/releases/download/v#{version}/kibble_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "432b17bb1fc3da99f44d981beab02417e4fd2f3ae658523fcaef0784f2d5e9b3"
      url "https://github.com/dcadolph/kibble/releases/download/v#{version}/kibble_#{version}_linux_amd64.tar.gz"
    end
  end

  name "kibble"
  desc "Run a README's documented install steps in a clean container so broken docs fail in CI"
  homepage "https://github.com/dcadolph/kibble"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "kibble"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/kibble"]
    end
  end

  # No zap stanza required
end
