# This file was generated by GoReleaser. DO NOT EDIT.
cask "kibble" do
  version "0.16.0"

  on_macos do
    on_arm do
      sha256 "f1c38b4a49fe93bbc96a54e8428d5bf89cfcded8a73ccdae83e37c320cad97e0"
      url "https://github.com/dcadolph/kibble/releases/download/v#{version}/kibble_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "fd4571a8e99984ce6b59b1fd8f4b9233aa0749d5ca38342e6b078771b20ef1f9"
      url "https://github.com/dcadolph/kibble/releases/download/v#{version}/kibble_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "54df9c49d5eb8d6cf699e160ed2e96d80e60469731066b97ca58984fab93ed7c"
      url "https://github.com/dcadolph/kibble/releases/download/v#{version}/kibble_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "7dba40e6614a7b2381aca69b107e0884674dbe9c8c6525ec70dcf953dbb51e8f"
      url "https://github.com/dcadolph/kibble/releases/download/v#{version}/kibble_#{version}_linux_amd64.tar.gz"
    end
  end

  name "kibble"
  desc "Run a README's documented install steps in a clean container so broken docs fail in CI"
  homepage "https://github.com/dcadolph/kibble"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "kibble"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/kibble"]
    end
  end

  # No zap stanza required
end
