# This file was generated by GoReleaser. DO NOT EDIT.
cask "kibble" do
  version "0.17.0"

  on_macos do
    on_arm do
      sha256 "fa2538a68c23ce1fc72f4f5ba813aa3e84adf3f87b8ff700e9ede5a74ce5942b"
      url "https://github.com/dcadolph/kibble/releases/download/v#{version}/kibble_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "0c700fa1f2c30127e650260cbaf98b9b5a087862eea9fa719e1a92e2303ae8d8"
      url "https://github.com/dcadolph/kibble/releases/download/v#{version}/kibble_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "a97df95e0cff1a810186b5a0335994c359d5526c1873aa791cc0616f96e5f349"
      url "https://github.com/dcadolph/kibble/releases/download/v#{version}/kibble_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "33c9cb0f366a0f8bb4c191787a8ac24185fa57edabf41bf0a87d370afa648f80"
      url "https://github.com/dcadolph/kibble/releases/download/v#{version}/kibble_#{version}_linux_amd64.tar.gz"
    end
  end

  name "kibble"
  desc "Run a README's documented install steps in a clean container so broken docs fail in CI"
  homepage "https://github.com/dcadolph/kibble"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "kibble"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/kibble"]
    end
  end

  # No zap stanza required
end
