# This file was generated by GoReleaser. DO NOT EDIT.
cask "preen" do
  version "2.2.1"

  on_macos do
    on_arm do
      sha256 "988cda5d58ca681e976a598dc03cb26833f6a95804306f45f47ba271743f5ebe"
      url "https://github.com/dcadolph/preen/releases/download/v#{version}/preen_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "8c58636adb4ccf57e3b5e3bf49f1011cda91e24483c001aea080abab98372466"
      url "https://github.com/dcadolph/preen/releases/download/v#{version}/preen_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "6b7dc86bb2d99e8fee615d7e7e59da855aa8eaa0a0e7ad4d0319ad2cb1197456"
      url "https://github.com/dcadolph/preen/releases/download/v#{version}/preen_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "bac74e4fb7a02ef12cf3a6e165c8900ef2e1ca7586feb9ddc1f7058c7501e962"
      url "https://github.com/dcadolph/preen/releases/download/v#{version}/preen_#{version}_linux_amd64.tar.gz"
    end
  end

  name "preen"
  desc "Turn a messy working tree or bad commits into clean, ordered, atomic commits"
  homepage "https://github.com/dcadolph/preen"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "preen"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/preen"]
    end
  end

  # No zap stanza required
end
