# This file was generated by GoReleaser. DO NOT EDIT.
cask "preen" do
  version "2.0.0"

  on_macos do
    on_intel do
      sha256 "1f181fdf7cd1fb076f12bd608e7932a2ed43b05e7c425f07ae06a350013bec2a"
      url "https://github.com/dcadolph/preen/releases/download/v#{version}/preen_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "6e3638883bd2f748f79537c12d22d43ddcafa1d6a99511fd684a5ee93653a033"
      url "https://github.com/dcadolph/preen/releases/download/v#{version}/preen_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "fbc73a93f9adf860e09f40090152b86df525f97c0be4b3bba0cb6a5f1fe1d76b"
      url "https://github.com/dcadolph/preen/releases/download/v#{version}/preen_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "467f4093ca8e9ee635e0983c6e8af3daf26a8047416cd635295156093aba8f78"
      url "https://github.com/dcadolph/preen/releases/download/v#{version}/preen_#{version}_linux_arm64.tar.gz"
    end
  end

  name "preen"
  desc "Turn a messy working tree or bad commits into clean, ordered, atomic commits"
  homepage "https://github.com/dcadolph/preen"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "preen"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/preen"]
    end
  end

  # No zap stanza required

end
