# This file was generated by GoReleaser. DO NOT EDIT.
cask "preen" do
  version "2.2.0"

  on_macos do
    on_arm do
      sha256 "9d4da287725aa250014eac40e57bcadcfdeebb7cde9b36ceee1d01c59a76dbe9"
      url "https://github.com/dcadolph/preen/releases/download/v#{version}/preen_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "7fd515f6af174f29ef2c0d595e2805fffaf64647036974269e185a02d7e45079"
      url "https://github.com/dcadolph/preen/releases/download/v#{version}/preen_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "fb55cf922bef86033c15fdbbdf16544132e625a74c8f5ac2f369665bb2b21d6a"
      url "https://github.com/dcadolph/preen/releases/download/v#{version}/preen_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "e8367b0c5255f03c7959dd2ab8786167dcd6acf56d6e06a858ebd4779fda8eb5"
      url "https://github.com/dcadolph/preen/releases/download/v#{version}/preen_#{version}_linux_amd64.tar.gz"
    end
  end

  name "preen"
  desc "Turn a messy working tree or bad commits into clean, ordered, atomic commits"
  homepage "https://github.com/dcadolph/preen"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "preen"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/preen"]
    end
  end

  # No zap stanza required
end
